"""Add retry count to job

Revision ID: 4a0b2dc9d5d5
Revises: 96729e417c11
Create Date: 2026-07-30 16:49:00.147111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0b2dc9d5d5'
down_revision: Union[str, Sequence[str], None] = '96729e417c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=False,server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
