""" add users and job ownership

Revision ID: caef4d69c665
Revises: 4a0b2dc9d5d5
Create Date: 2026-09-11 14:28:46.641674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caef4d69c665'
down_revision: Union[str, Sequence[str], None] = '4a0b2dc9d5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.execute("""
    INSERT INTO users (id, username, email, password_hash, role, is_active)
                    VALUES (0, 'admin', 'admin@example.com', 'PLACEHOLDER_HASH', 'admin', TRUE)
    """)

    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE jobs SET user_id = 0 WHERE user_id IS NULL")
    op.alter_column('jobs', 'user_id', existing_type=sa.Integer(), nullable=False)
    op.create_foreign_key('fk_jobs_user_id_users', 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_user_id_users', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
